## What is statistics?

Probability theory computes probabilities of complex events given the underlying base probabilities.

Statistics takes us in the opposite direction.

We are given **data** that was generated by a **Stochastic process**

We **infer** properties of the underlying base probabilities.

## Example deciding whether a coin is biased.

In a previous video we discussed the distribution of the number of heads when flipping a fair coin many times.

Let's flip the question around: we flip a coin 1000 times and get 560 heads. 

Can we conclude that the coin is biased (not fair) ?

What can we conclude if we got 506 heads?

### The answer
The answer uses the following logic.

Suppose that the coin is fair. 

We can use **probability theory** to compute the probability of getting at least 560 (or 506) heads.

If this probability is very small, then we can **reject** <font color='red'>with confidence</font> the hypothesis that the coin is fair.

### Calculating the answer
We will learn how to calculate the probability *exactly*, but this can be tedious.

Instead, we can use the *Central Limit Theorem* which is easier to calculate and gives almost the same answer. 

We compute the **std** of the number of heads: $\sqrt{\frac{n}{4}}$ 

We then measure the difference between the number of heads we observed and 500 in units of **std**

In [15]:
%pylab inline
from math import sqrt
def compute_std(k,n):
    return (k-n/2.)/sqrt(n/4)
print 'for 560',compute_std(560,1000)
print 'for 506',compute_std(506,1000)

Populating the interactive namespace from numpy and matplotlib
for 560 3.7947331922
for 506 0.37947331922


We then use the **normal distribution** to compute the probability that a fair coin generated what we observe.

In [17]:
from scipy.special import erf

def calc_prob(k,n):
    s=compute_std(k,n)
    return (1.-erf(s))/2.

print 'for 560',calc_prob(560,1000)
print 'for 506',calc_prob(506,1000)

for 560 4.0125556322e-08
for 506 0.295752518497


### Conclusion
We see that the probability that an unbiased coin would generate a sequence with 560 or more heads is extremely small: $4\times 10^{-8}$ from which we can conclude, <font color='red'>with high confidence</font>, that the coin **is** biased.

On the other hand, a gap of 6 or more between the observed number of heads and 500 has probability of about 30%. So 506 does not provide evidence that the coin is biased.

### Other statistical questions
* Estimate the bias of the coin.
* Determine a *confidence interval* so that the true bias is within the interval <font color='red'>with confidence</font>,

## Some other examples
You might ask "why should I care whether a coin is biased?"

* This is a valid critique. 
* We will give two real-world cases in which we want to know whether a "coin" is biased or not.

### Case I: Polls
* Suppose elections will take place in a few days and we want to know how people plan to vote.
* Suppose there are just two parties: **D** and **R**.

* We could try and ask **all** potential voters.

* That would be very expensive.

* Instead, we can use a poll: call up a small randomly selected set of people.

* Call $n$ people at random and count the number of **D** votes.

* Can you say <font color='red'>with confidence</font> that there are more **D** votes, or more **R** votes?

* Mathematically equivalent to flipping a biased coin and 

* asking whether you can say <font color='red'>with confidence</font> that it is biased towards "Heads" or towards "Tails"

### Case 2: A/B testing
A common practice when optimizing a web page is to perform A/B tests.

* A/B refer to two alternative designs for the page.

* To see which design users prefer we randomly present design A or design B.

* We measure how long the user stayed on a page, or whether the user clicked on an advertisement.

* We want to decide, <font color='red'>with confidence</font>, which of the two designs is better.

* Again: similar to making a decision <font color='red'>with confidence</font> on whether "Heads" is more probably than "Tails" or vice versa.